"""
MASTER STRATEGY - COMPLETE IMPLEMENTATION
All Indicators & All Trading Strategies Combined
4-Hour Swing Trading Optimized
"""

import pandas as pd
import numpy as np
from datetime import datetime
from typing import Dict, List, Optional, Tuple
import sqlite3
import logging

# Import your existing indicator modules
from src.indicators.trend import calculate_sma, calculate_ema, calculate_adx, get_support_resistance
from src.indicators.momentum import calculate_rsi, calculate_macd, calculate_stochastic, calculate_cci
from src.indicators.volatility import calculate_atr, calculate_bollinger_bands
from src.indicators.volume import calculate_volume_sma, calculate_volume_ratio
from src.indicators.base import calculate_true_range

# Setup logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


# ============================================
# PART 1: TRADE SIGNAL CLASS
# ============================================

class TradeSignal:
    """
    Represents a trading signal generated by the strategy
    """

    def __init__(self,
                 ticker: str,
                 timestamp: datetime,
                 signal_type: str,  # BUY, SELL, HOLD
                 confidence: float,  # 0-100
                 entry_price: float,
                 stop_loss: float,
                 take_profit: float,
                 reason: str,
                 indicators_aligned: List[str],
                 strategy_used: str = "Master Strategy"):
        self.ticker = ticker
        self.timestamp = timestamp
        self.signal_type = signal_type  # BUY, SELL, HOLD
        self.confidence = confidence
        self.entry_price = entry_price
        self.stop_loss = stop_loss
        self.take_profit = take_profit
        self.reason = reason
        self.indicators_aligned = indicators_aligned
        self.strategy_used = strategy_used
        self.created_at = datetime.now()

    def to_dict(self):
        """Convert signal to dictionary for database storage"""
        return {
            'ticker': self.ticker,
            'timestamp': self.timestamp.isoformat(),
            'signal_type': self.signal_type,
            'confidence': self.confidence,
            'entry_price': self.entry_price,
            'stop_loss': self.stop_loss,
            'take_profit': self.take_profit,
            'reason': self.reason,
            'indicators': ','.join(self.indicators_aligned),
            'strategy': self.strategy_used,
            'risk_reward': round((self.take_profit - self.entry_price) / (self.entry_price - self.stop_loss),
                                 2) if self.stop_loss != self.entry_price else 0
        }

    def __repr__(self):
        return f"TradeSignal({self.signal_type}, {self.ticker}, {self.confidence:.0f}%, Risk:Reward {(self.take_profit - self.entry_price) / (self.entry_price - self.stop_loss):.2f}:1)"


# ============================================
# PART 2: MASTER STRATEGY CLASS
# ============================================

class MasterStrategy:
    """
    Complete Master Strategy Implementation
    Combines all indicators and strategies
    Optimized for 4-hour swing trading
    """

    def __init__(self, db_path: str = 'trading.db'):
        """Initialize strategy with optimized parameters"""

        self.db_path = db_path
        self.name = "Master Swing Trader - 4H Optimized"
        self.timeframe = "4H"
        self.version = "2.0 - Complete Implementation"

        # ===== TREND PARAMETERS =====
        self.ma_fast = 50  # SMA fast period
        self.ma_slow = 200  # SMA slow period

        # ===== MOMENTUM PARAMETERS =====
        self.rsi_period = 14
        self.rsi_buy_lower = 30  # Buy zone lower
        self.rsi_buy_upper = 45  # Buy zone upper
        self.rsi_sell_lower = 55  # Sell zone lower
        self.rsi_sell_upper = 70  # Sell zone upper

        self.macd_fast = 12
        self.macd_slow = 26
        self.macd_signal = 9

        self.stoch_k_period = 14
        self.stoch_k_smooth = 3
        self.stoch_d_smooth = 3
        self.stoch_oversold = 30
        self.stoch_overbought = 70

        self.cci_period = 20
        self.cci_overbought = 100
        self.cci_oversold = -100

        # ===== VOLATILITY PARAMETERS =====
        self.atr_period = 14
        self.atr_stop_multiple = 2.0  # Stop loss: 2 ATR
        self.atr_tp_multiple = 3.0  # Take profit: 3 ATR

        self.bb_period = 20
        self.bb_std_dev = 2.0

        # ===== TREND STRENGTH FILTER =====
        self.adx_period = 14
        self.adx_threshold = 25  # Minimum ADX for strong trend

        # ===== VOLUME FILTER =====
        self.volume_period = 20
        self.volume_ratio_min = 1.0  # Volume must be > average

        # ===== SUPPORT/RESISTANCE =====
        self.support_resistance_period = 20

        # ===== SIGNAL REQUIREMENTS (OPTIMIZED) =====
        self.min_buy_signals = 3  # Need 3+ buy signals
        self.min_buy_confidence = 65  # 65% minimum (increased from 50)
        self.min_sell_signals = 3  # Need 3+ sell signals (increased from 2)
        self.min_sell_confidence = 65  # 65% minimum (increased from 50)

        # ===== RISK MANAGEMENT =====
        self.risk_per_trade = 0.02  # 2% of account
        self.min_risk_reward = 1.5  # Minimum 1:1.5

        # Initialize database
        self._init_database()

        logger.info(f"✓ {self.name} initialized")
        logger.info(f"  Buy requirements: {self.min_buy_signals}+ signals, ≥{self.min_buy_confidence}% confidence")
        logger.info(f"  Sell requirements: {self.min_sell_signals}+ signals, ≥{self.min_sell_confidence}% confidence")

    def _init_database(self):
        """Create database tables if not exist"""
        conn = sqlite3.connect(self.db_path)
        cursor = conn.cursor()

        # Signals table
        cursor.execute('''
            CREATE TABLE IF NOT EXISTS signals (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                ticker TEXT NOT NULL,
                timestamp DATETIME NOT NULL,
                signal_type TEXT,
                confidence REAL,
                entry_price REAL,
                stop_loss REAL,
                take_profit REAL,
                risk_reward REAL,
                reason TEXT,
                indicators TEXT,
                strategy TEXT,
                created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
                actioned INTEGER DEFAULT 0,
                UNIQUE(ticker, timestamp, signal_type)
            )
        ''')

        conn.commit()
        conn.close()

    # ============================================
    # PART 3: INDICATOR CALCULATIONS
    # ============================================

    def calculate_all_indicators(self, df: pd.DataFrame) -> pd.DataFrame:
        """
        Calculate all 20+ technical indicators
        Uses indicator modules from src/indicators/
        """

        close = df['Close']
        high = df['High']
        low = df['Low']
        volume = df['Volume']

        logger.info("📊 Calculating indicators...")

        # ===== TREND INDICATORS =====
        df['SMA_50'] = calculate_sma(close, self.ma_fast)
        df['SMA_200'] = calculate_sma(close, self.ma_slow)
        df['EMA_12'] = calculate_ema(close, 12)
        df['EMA_26'] = calculate_ema(close, 26)

        # ===== TREND STRENGTH =====
        df['ADX'] = calculate_adx(high, low, close, self.adx_period)

        # ===== MOMENTUM INDICATORS =====
        df['RSI'] = calculate_rsi(close, self.rsi_period)

        df['MACD'], df['MACD_Signal'], df['MACD_Hist'] = calculate_macd(
            close, self.macd_fast, self.macd_slow, self.macd_signal
        )

        df['Stoch_K'], df['Stoch_D'] = calculate_stochastic(
            high, low, close, self.stoch_k_period, self.stoch_k_smooth, self.stoch_d_smooth
        )

        df['CCI'] = calculate_cci(high, low, close, self.cci_period)

        # ===== VOLATILITY INDICATORS =====
        df['ATR'] = calculate_atr(high, low, close, self.atr_period)

        df['BB_Upper'], df['BB_Middle'], df['BB_Lower'] = calculate_bollinger_bands(
            close, self.bb_period, self.bb_std_dev
        )

        # ===== VOLUME INDICATORS =====
        df['Volume_SMA'] = calculate_volume_sma(volume, self.volume_period)
        df['Volume_Ratio'] = calculate_volume_ratio(volume, df['Volume_SMA'])

        # ===== SUPPORT & RESISTANCE =====
        df['Support'], df['Resistance'] = get_support_resistance(high, low, self.support_resistance_period)

        # ===== TREND DIRECTION =====
        df['Trend_Up'] = df['SMA_50'] > df['SMA_200']
        df['Trend_Down'] = df['SMA_50'] < df['SMA_200']
        df['Trend_Strong'] = df['ADX'] > self.adx_threshold

        logger.info("✓ All indicators calculated successfully")

        return df

    # ============================================
    # PART 4: SIGNAL GENERATION (BUY & SELL)
    # ============================================

    def generate_signals(self, ticker: str, df: pd.DataFrame) -> List[TradeSignal]:
        """
        Generate trading signals for a stock
        Combines all strategies for best results

        Args:
            ticker: Stock symbol (e.g., 'AAPL')
            df: DataFrame with OHLCV data

        Returns:
            List of TradeSignal objects
        """

        signals = []

        # Calculate all indicators
        df = self.calculate_all_indicators(df)

        # Need enough data for indicators to settle
        if len(df) < 200:
            logger.warning(f"⚠ Insufficient data for {ticker} (need 200+ candles, have {len(df)})")
            return signals

        # Evaluate most recent candle
        i = len(df) - 1
        signal = self._evaluate_candle(df, i, ticker)

        if signal and signal.signal_type != 'HOLD':
            signals.append(signal)
            logger.info(f"🎯 {signal}")

        return signals

    def _evaluate_candle(self, df: pd.DataFrame, i: int, ticker: str) -> Optional[TradeSignal]:
        """
        Evaluate single candle for BUY and SELL signals
        Main logic for signal generation
        """

        # Get current values
        close = df['Close'].iloc[i]
        high = df['High'].iloc[i]
        low = df['Low'].iloc[i]
        volume = df['Volume'].iloc[i]

        # Get indicator values
        sma50 = df['SMA_50'].iloc[i]
        sma200 = df['SMA_200'].iloc[i]
        adx = df['ADX'].iloc[i]
        rsi = df['RSI'].iloc[i]
        macd = df['MACD'].iloc[i]
        macd_signal = df['MACD_Signal'].iloc[i]
        macd_hist = df['MACD_Hist'].iloc[i]
        stoch_k = df['Stoch_K'].iloc[i]
        stoch_d = df['Stoch_D'].iloc[i]
        cci = df['CCI'].iloc[i]
        atr = df['ATR'].iloc[i]
        bb_upper = df['BB_Upper'].iloc[i]
        bb_middle = df['BB_Middle'].iloc[i]
        bb_lower = df['BB_Lower'].iloc[i]
        volume_sma = df['Volume_SMA'].iloc[i]
        support = df['Support'].iloc[i]
        resistance = df['Resistance'].iloc[i]

        # Previous candle values (for crossovers)
        prev_macd = df['MACD'].iloc[i - 1] if i > 0 else macd
        prev_macd_signal = df['MACD_Signal'].iloc[i - 1] if i > 0 else macd_signal
        prev_stoch_k = df['Stoch_K'].iloc[i - 1] if i > 0 else stoch_k
        prev_stoch_d = df['Stoch_D'].iloc[i - 1] if i > 0 else stoch_d
        prev_close = df['Close'].iloc[i - 1] if i > 0 else close

        # ===== TREND ANALYSIS =====
        trend_up = sma50 > sma200
        trend_down = sma50 < sma200
        trend_strong = adx > self.adx_threshold
        volume_valid = volume >= volume_sma * self.volume_ratio_min

        # ===== BUY SIGNAL EVALUATION =====
        buy_signals = []
        buy_confidence = 0

        # Filter 1: Must be in uptrend
        if trend_up:
            buy_signals.append('UPTREND')
            buy_confidence += 15
        else:
            return None

        # Filter 2: Trend must be strong
        if trend_strong:
            buy_signals.append('STRONG_TREND')
            buy_confidence += 15
        else:
            return None

        # Filter 3: Volume confirmation
        if volume_valid:
            buy_signals.append('VOLUME_ABOVE_AVG')
            buy_confidence += 10
        else:
            return None

        # Buy Signal 1: Price above 50 SMA
        if close > sma50:
            buy_signals.append('PRICE_ABOVE_SMA50')
            buy_confidence += 15

        # Buy Signal 2: RSI Momentum Entry (30-45 zone)
        if self.rsi_buy_lower < rsi < self.rsi_buy_upper:
            buy_signals.append('RSI_MOMENTUM_ZONE')
            buy_confidence += 25

        # Buy Signal 3: MACD Bullish Cross
        if prev_macd <= prev_macd_signal and macd > macd_signal:
            buy_signals.append('MACD_BULLISH_CROSS')
            buy_confidence += 25
        elif macd > macd_signal:
            buy_signals.append('MACD_ABOVE_SIGNAL')
            buy_confidence += 15

        # Buy Signal 4: Stochastic Bullish Cross (Oversold)
        if prev_stoch_k <= prev_stoch_d and stoch_k > stoch_d:
            if stoch_k < self.stoch_oversold:
                buy_signals.append('STOCH_OVERSOLD_CROSS')
                buy_confidence += 25

        # Buy Signal 5: CCI Positive Reversal
        if cci > -50 and cci < self.cci_oversold:
            buy_signals.append('CCI_OVERSOLD_ZONE')
            buy_confidence += 15

        # Buy Signal 6: Bollinger Band Lower Touch
        if close < bb_lower * 1.01 and close > bb_lower * 0.99:
            buy_signals.append('BB_LOWER_TOUCH')
            buy_confidence += 20

        # Buy Signal 7: Support Level Bounce
        if close > support and close < support * 1.02 and volume_valid:
            buy_signals.append('SUPPORT_BOUNCE')
            buy_confidence += 20

        # Buy Signal 8: Above Middle Bollinger Band with Volume
        if close > bb_middle and close > prev_close and volume_valid:
            buy_signals.append('PRICE_ABOVE_BB_MIDDLE')
            buy_confidence += 15

        # Buy Signal 9: Bullish Divergence (EMA cross)
        ema12 = df['EMA_12'].iloc[i]
        ema26 = df['EMA_26'].iloc[i]
        if ema12 > ema26:
            buy_signals.append('EMA_BULLISH_CROSS')
            buy_confidence += 15

        # ===== GENERATE BUY SIGNAL =====
        if len(buy_signals) >= self.min_buy_signals and \
                buy_confidence >= self.min_buy_confidence:

            # Calculate stops and targets
            stop_loss = close - (self.atr_stop_multiple * atr)
            take_profit = close + (self.atr_tp_multiple * atr)

            # Verify risk/reward
            if take_profit == close or stop_loss == close:
                return None

            risk_reward = (take_profit - close) / (close - stop_loss)
            if risk_reward < self.min_risk_reward:
                return None

            return TradeSignal(
                ticker=ticker,
                timestamp=df.index[i],
                signal_type='BUY',
                confidence=min(buy_confidence, 100),
                entry_price=close,
                stop_loss=stop_loss,
                take_profit=take_profit,
                reason=f'{len(buy_signals)} signals: {", ".join(buy_signals[:3])}...',
                indicators_aligned=buy_signals,
                strategy_used='Master Strategy - BUY'
            )

        # ===== SELL SIGNAL EVALUATION =====
        sell_signals = []
        sell_confidence = 0

        # Sell Signal 1: Downtrend
        if trend_down:
            sell_signals.append('DOWNTREND')
            sell_confidence += 20

        # Sell Signal 2: RSI Overbought (55-70)
        if self.rsi_sell_lower < rsi < self.rsi_sell_upper:
            sell_signals.append('RSI_OVERBOUGHT')
            sell_confidence += 25

        # Sell Signal 3: MACD Bearish Cross
        if prev_macd >= prev_macd_signal and macd < macd_signal:
            sell_signals.append('MACD_BEARISH_CROSS')
            sell_confidence += 25
        elif macd < macd_signal:
            sell_signals.append('MACD_BELOW_SIGNAL')
            sell_confidence += 15

        # Sell Signal 4: Stochastic Bearish Cross (Overbought)
        if prev_stoch_k >= prev_stoch_d and stoch_k < stoch_d:
            if stoch_k > self.stoch_overbought:
                sell_signals.append('STOCH_OVERBOUGHT_CROSS')
                sell_confidence += 25

        # Sell Signal 5: CCI Overbought
        if cci > self.cci_overbought:
            sell_signals.append('CCI_OVERBOUGHT')
            sell_confidence += 15

        # Sell Signal 6: Bollinger Band Upper Touch
        if close > bb_upper * 0.99 and close < bb_upper * 1.01:
            sell_signals.append('BB_UPPER_TOUCH')
            sell_confidence += 20

        # Sell Signal 7: Resistance Level Rejection
        if close > resistance * 0.98 and close < resistance * 1.02 and volume_valid:
            sell_signals.append('RESISTANCE_REJECTION')
            sell_confidence += 20

        # Sell Signal 8: Below Bollinger Middle
        if close < bb_middle and close < prev_close and volume_valid:
            sell_signals.append('PRICE_BELOW_BB_MIDDLE')
            sell_confidence += 15

        # Sell Signal 9: Bearish Divergence (EMA cross)
        if ema12 < ema26:
            sell_signals.append('EMA_BEARISH_CROSS')
            sell_confidence += 15

        # Sell Signal 10: Trend Weakening (ADX dropping)
        prev_adx = df['ADX'].iloc[i - 1] if i > 0 else adx
        if prev_adx > adx and adx < 20:
            sell_signals.append('TREND_WEAKENING')
            sell_confidence += 15

        # ===== GENERATE SELL SIGNAL =====
        if len(sell_signals) >= self.min_sell_signals and \
                sell_confidence >= self.min_sell_confidence:

            # For sell signals, stops and targets are reversed
            stop_loss = close + (self.atr_stop_multiple * atr)
            take_profit = close - (self.atr_tp_multiple * atr)

            # Verify risk/reward
            if take_profit == close or stop_loss == close:
                return None

            risk_reward = (close - take_profit) / (stop_loss - close)
            if risk_reward < self.min_risk_reward:
                return None

            return TradeSignal(
                ticker=ticker,
                timestamp=df.index[i],
                signal_type='SELL',
                confidence=min(sell_confidence, 100),
                entry_price=close,
                stop_loss=stop_loss,
                take_profit=take_profit,
                reason=f'{len(sell_signals)} signals: {", ".join(sell_signals[:3])}...',
                indicators_aligned=sell_signals,
                strategy_used='Master Strategy - SELL'
            )

        # No strong signal
        return TradeSignal(
            ticker=ticker,
            timestamp=df.index[i],
            signal_type='HOLD',
            confidence=0,
            entry_price=close,
            stop_loss=0,
            take_profit=0,
            reason='Insufficient signal alignment',
            indicators_aligned=[],
            strategy_used='Hold'
        )

    # ============================================
    # PART 5: DATABASE OPERATIONS
    # ============================================

    def store_signal(self, signal: TradeSignal) -> bool:
        """Store signal in database"""
        conn = sqlite3.connect(self.db_path)
        cursor = conn.cursor()

        signal_dict = signal.to_dict()

        try:
            cursor.execute('''
                INSERT INTO signals 
                (ticker, timestamp, signal_type, confidence, entry_price, 
                 stop_loss, take_profit, risk_reward, reason, indicators, strategy)
                VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
            ''', (
                signal_dict['ticker'],
                signal_dict['timestamp'],
                signal_dict['signal_type'],
                signal_dict['confidence'],
                signal_dict['entry_price'],
                signal_dict['stop_loss'],
                signal_dict['take_profit'],
                signal_dict['risk_reward'],
                signal_dict['reason'],
                signal_dict['indicators'],
                signal_dict['strategy']
            ))

            conn.commit()
            logger.info(f"✓ Signal stored: {signal.ticker} {signal.signal_type}")
            conn.close()
            return True

        except sqlite3.IntegrityError as e:
            logger.warning(f"⚠ Signal already exists: {signal.ticker}")
            conn.close()
            return False
        except Exception as e:
            logger.error(f"✗ Error storing signal: {e}")
            conn.close()
            return False

    def get_recent_signals(self, limit: int = 20, signal_type: str = None) -> List[Dict]:
        """Get recent signals from database"""
        conn = sqlite3.connect(self.db_path)
        cursor = conn.cursor()

        if signal_type:
            cursor.execute('''
                SELECT * FROM signals 
                WHERE signal_type = ?
                ORDER BY timestamp DESC 
                LIMIT ?
            ''', (signal_type, limit))
        else:
            cursor.execute('''
                SELECT * FROM signals 
                ORDER BY timestamp DESC 
                LIMIT ?
            ''', (limit,))

        columns = [description[0] for description in cursor.description]
        signals = [dict(zip(columns, row)) for row in cursor.fetchall()]

        conn.close()
        return signals

    def get_signal_stats(self) -> Dict:
        """Get statistics on generated signals"""
        conn = sqlite3.connect(self.db_path)
        cursor = conn.cursor()

        cursor.execute('SELECT COUNT(*) FROM signals WHERE signal_type = "BUY"')
        buy_count = cursor.fetchone()[0]

        cursor.execute('SELECT COUNT(*) FROM signals WHERE signal_type = "SELL"')
        sell_count = cursor.fetchone()[0]

        cursor.execute('SELECT AVG(confidence) FROM signals WHERE signal_type = "BUY"')
        avg_buy_conf = cursor.fetchone()[0] or 0

        cursor.execute('SELECT AVG(confidence) FROM signals WHERE signal_type = "SELL"')
        avg_sell_conf = cursor.fetchone()[0] or 0

        conn.close()

        return {
            'total_buy_signals': buy_count,
            'total_sell_signals': sell_count,
            'avg_buy_confidence': round(avg_buy_conf, 2),
            'avg_sell_confidence': round(avg_sell_conf, 2),
            'total_signals': buy_count + sell_count
        }


# ============================================
# PART 6: EXAMPLE USAGE
# ============================================

# if __name__ == "__main__":
#
#     import yfinance as yf
#
#     print("\n" + "=" * 80)
#     print("MASTER STRATEGY - COMPLETE IMPLEMENTATION")
#     print("=" * 80)
#
#     # Initialize strategy
#     strategy = MasterStrategy(db_path='trading.db')
#
#     print(f"\n{strategy.name}")
#     print(f"Version: {strategy.version}")
#     print(f"Timeframe: {strategy.timeframe}")
#
#     # Test on multiple stocks
#     tickers = ["AAPL", "MSFT", "GOOGL"]
#
#     for ticker in tickers:
#         print(f"\n{'=' * 80}")
#         print(f"Processing: {ticker}")
#         print(f"{'=' * 80}")
#
#         try:
#             # Download data
#             print(f"📥 Downloading data for {ticker}...")
#             df = yf.download(ticker, start="2022-01-01", end="2024-01-01", progress=False)
#
#             print(f"✓ Downloaded {len(df)} candles")
#
#             # Generate signals
#             print(f"🔍 Generating signals...")
#             signals = strategy.generate_signals(ticker, df)
#
#             # Store and display signals
#             if signals:
#                 for signal in signals:
#                     strategy.store_signal(signal)
#                     print(f"  {signal}")
#             else:
#                 print("  No signals generated for this candle")
#
#         except Exception as e:
#             print(f"✗ Error processing {ticker}: {e}")
#
#     # Display statistics
#     print(f"\n{'=' * 80}")
#     print("SIGNAL STATISTICS")
#     print(f"{'=' * 80}")
#     stats = strategy.get_signal_stats()
#     for key, value in stats.items():
#         print(f"{key.replace('_', ' ').title()}: {value}")
#
#     # Display recent signals
#     print(f"\n{'=' * 80}")
#     print("RECENT SIGNALS (Last 10)")
#     print(f"{'=' * 80}")
#     recent = strategy.get_recent_signals(limit=10)
#     for signal in recent:
#         print(f"{signal['ticker']}: {signal['signal_type']} @ ${signal['entry_price']:.2f} | "
#               f"Confidence: {signal['confidence']:.0f}% | R:R {signal['risk_reward']:.2f}")
#
#     print(f"\n{'=' * 80}")
#     print("✓ MASTER STRATEGY COMPLETE")
#     print(f"{'=' * 80}\n")