from flask import Blueprint, jsonify
import sqlite3

signals_bp = Blueprint('signals', __name__)


@signals_bp.route('/active', methods=['GET'])
def get_active_signals():
    # Connect directly to the database generated by setup.py to grab signals
    try:
        conn = sqlite3.connect("trading.db")
        conn.row_factory = sqlite3.Row
        cursor = conn.cursor()

        cursor.execute("SELECT * FROM signals WHERE actioned = 0 ORDER BY timestamp DESC")
        rows = cursor.fetchall()
        signals = [dict(row) for row in rows]

        conn.close()
        return jsonify({"status": "success", "signals": signals})
    except Exception as e:
        return jsonify({"status": "error", "message": str(e)}), 500